### ISSUE TITLE
Extremely long time taken for comparison of codes

### ISSUE THREAD

**Issue by jackswl** [neulab/code-bert-score#10]
Hi all,

Thanks for the wonderful work. 

I am currently running code_bert_score to evaluate the similarity between generated code and 'correct' code. However, it just takes way too long locally. Is there a way for it to speedup (i.e. using GPU or something) on MacOS? Are you able to let me know where I can optimize the code? Is there some specific settings I have to update for the code to run faster? Thanks!

```
import code_bert_score
import pandas as pd

rp_values = [1]

for rp in rp_values:
    CSV_PATH = f'xxx'
    codebertdf = pd.read_csv(CSV_PATH)

    codebertdf['generated_output'] = codebertdf['generated_output'].str.strip()

    predictions = codebertdf['generated_output'].tolist()
    refs = codebertdf['actual_output'].tolist()
    
    # Calculate BERT scores
    P, R, F3, F1 = code_bert_score.score(cands=predictions, refs=refs, lang='python')
    
    # Add scores to DataFrame
    codebertdf['P'] = P
    codebertdf['R'] = R
    codebertdf['F3'] = F3
    codebertdf['F1'] = F1
    
    # Export DataFrame
    codebertdf.to_csv(f'/xxx', index=False)
```

**Comment by urialon** [comment]
Hi Jack,
Thank you for your interest in our work!

Yes, a GPU will definitely speed this up.
You can also use a Google colab with a GPU.

Best,
Uri

**Comment by jackswl** [comment]
Hi @urialon, great work again. 

Yeah, using a google Colab (with GPU) will speed it up. However, I am intending to run it locally on my macbook. 

Is there any settings I should do for my code above, for the code_bert_score to somehow tap into my macbook m3 chips?

Thanks!
