### ISSUE TITLE
Request of Evaluation on Human Preference Experiments

### ISSUE THREAD

**Issue by VichyTong** [neulab/code-bert-score#7]
I came across the paper [CodeBERTScore: Evaluating Code Generation with Pretrained Models of Code](https://arxiv.org/abs/2302.05527) which mentions that CodeBERTScore is evaluated on CoNaLa.

> ## Human Preference Experiments
> We evaluate on CoNaLa (Yin et al., 2018a), a natural language
> context to python code generation benchmark collected from StackOverflow. We use the human
> annotation released by Evtikhiev et al. (2022) to measure the correlation between each metric and
> human preference. For each example, Evtikhiev et al. (2022) asked experienced software developers
> to grade the generated code snippets from five different models. The grade scales from zero to four,
> with zero meaning that the generated code is irrelevant and unhelpful, and four meaning that the
> generated code solves the problem accurately. Overall, there are 2860 annotated code snippets (5
> generations × 472 examples) where each snippet is graded by 4.5 annotators.

 I checked `./evaluation`, but only found the humaneval dataset. Would you be kind enough to share the code used for this evaluation?

**Comment by urialon** [comment]
Hi @VichyTong ,
Thank you for your interest in our work!

As far as I know, the annotations of Evtikhiev et al. (2022) are not publicly available, but Evtikhiev et al. have kindly agreed to share them with us.

@shuyanzhou am I correct? Can we share our evaluation _code_, and if Evtikhiev et al. will share their data, our code will work?

Best,
Uri

**Comment by shuyanzhou** [comment]
> As far as I know, the annotations of Evtikhiev et al. (2022) are not publicly available, but Evtikhiev et al. have kindly agreed to share them with us.

This is correct. The same code should work regardless of the dataset as long as all data are processed to the same format.

**Comment by VichyTong** [comment]
Hi @urialon and @shuyanzhou ,

Thanks for your reply, I will check Evtikhiev et al. (2022) for their work.

Best,
Weixi
